Traceback (most recent call last):
  File "/home/tiagoburiol/.local/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiagoburiol/anaconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tiagoburiol/anaconda3/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x = np.linspace(-3, 3.7)
f = lambda x: 0.3*(x+1)*(x-2.1)*(1.1*x)-1.1
fig, ax = plt.subplots()
ax.plot(x, f(x),[2.485],f(2.485),'o',color='black')


params = {'mathtext.default': 'regular' }          
plt.rcParams.update(params)


ax.text(-0.2,-0.7, "O", style='italic')
ax.text(1.05,-0.7, "a", style='italic')
ax.text(2.55,f(2.485)-0.8, "$\overline{x}$", style='italic')
ax.text(3,-0.7, "b", style='italic')

ax.text(-0.35,f(1)-0.2, "f(a)", style='italic')
ax.text(-0.35,f(3)-0.2, "f(b)", style='italic')


ax.vlines(x=[1,3], ymin=[0,0], ymax=[f(1),f(3)], 
          color='black', ls='--', lw=1)

ax.hlines(y=[f(1),f(3)],xmin=[0,0], xmax=[1,3], 
          color='black', ls='--', lw=1)


           
# CustomizaÃ§Ãµes para a figura final:
#____________________
# Limites em x e em y
ymin = -4; ymax = 10
xmin = -1; xmax = 5
plt.ylim(ymin, ymax) 
plt.xlim(xmin, xmax)
#________________________________________________
# Inclui setas nos eixos nas posiÃ§Ãµes certas
ax.plot((xmax-0.07), (0), marker=">", color='black')
ax.text(xmax-0.15,-1, "x", style='italic')
ax.plot((0), (ymax-0.3), marker="^",color='black')
ax.text(-0.2, ymax-0.7, "y", style='italic')

# remove as bordas
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['bottom'].set_visible(False)
ax.spines['left'].set_visible(False)

# desenha os eixos
ax.axhline(linewidth=1.0, color='black')
ax.axvline(linewidth=1.0, color='black')


plt.xticks([])
plt.yticks([])
plt.grid()
plt.savefig('png/bolzano.png',dpi=300)
------------------

----- stderr -----
<>:13: SyntaxWarning: invalid escape sequence '\o'
<>:13: SyntaxWarning: invalid escape sequence '\o'
/tmp/ipykernel_41173/3091409264.py:13: SyntaxWarning: invalid escape sequence '\o'
  ax.text(2.55,f(2.485)-0.8, "$\overline{x}$", style='italic')
----- stderr -----
/tmp/ipykernel_41173/3091409264.py:13: SyntaxWarning: invalid escape sequence '\o'
  ax.text(2.55,f(2.485)-0.8, "$\overline{x}$", style='italic')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 56[0m
[1;32m     54[0m plt[38;5;241m.[39myticks([])
[1;32m     55[0m plt[38;5;241m.[39mgrid()
[0;32m---> 56[0m plt[38;5;241m.[39msavefig([38;5;124m'[39m[38;5;124mpng/bolzano.png[39m[38;5;124m'[39m,dpi[38;5;241m=[39m[38;5;241m300[39m)

File [0;32m~/anaconda3/lib/python3.12/site-packages/matplotlib/pyplot.py:1134[0m, in [0;36msavefig[0;34m(*args, **kwargs)[0m
[1;32m   1131[0m fig [38;5;241m=[39m gcf()
[1;32m   1132[0m [38;5;66;03m# savefig default implementation has no return, so mypy is unhappy[39;00m
[1;32m   1133[0m [38;5;66;03m# presumably this is here because subclasses can return?[39;00m
[0;32m-> 1134[0m res [38;5;241m=[39m fig[38;5;241m.[39msavefig([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)  [38;5;66;03m# type: ignore[func-returns-value][39;00m
[1;32m   1135[0m fig[38;5;241m.[39mcanvas[38;5;241m.[39mdraw_idle()  [38;5;66;03m# Need this if 'transparent=True', to reset colors.[39;00m
[1;32m   1136[0m [38;5;28;01mreturn[39;00m res

File [0;32m~/anaconda3/lib/python3.12/site-packages/matplotlib/figure.py:3390[0m, in [0;36mFigure.savefig[0;34m(self, fname, transparent, **kwargs)[0m
[1;32m   3388[0m     [38;5;28;01mfor[39;00m ax [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39maxes:
[1;32m   3389[0m         _recursively_make_axes_transparent(stack, ax)
[0;32m-> 3390[0m [38;5;28mself[39m[38;5;241m.[39mcanvas[38;5;241m.[39mprint_figure(fname, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.12/site-packages/matplotlib/backend_bases.py:2193[0m, in [0;36mFigureCanvasBase.print_figure[0;34m(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)[0m
[1;32m   2189[0m [38;5;28;01mtry[39;00m:
[1;32m   2190[0m     [38;5;66;03m# _get_renderer may change the figure dpi (as vector formats[39;00m
[1;32m   2191[0m     [38;5;66;03m# force the figure dpi to 72), so we need to set it again here.[39;00m
[1;32m   2192[0m     [38;5;28;01mwith[39;00m cbook[38;5;241m.[39m_setattr_cm([38;5;28mself[39m[38;5;241m.[39mfigure, dpi[38;5;241m=[39mdpi):
[0;32m-> 2193[0m         result [38;5;241m=[39m print_method(
[1;32m   2194[0m             filename,
[1;32m   2195[0m             facecolor[38;5;241m=[39mfacecolor,
[1;32m   2196[0m             edgecolor[38;5;241m=[39medgecolor,
[1;32m   2197[0m             orientation[38;5;241m=[39morientation,
[1;32m   2198[0m             bbox_inches_restore[38;5;241m=[39m_bbox_inches_restore,
[1;32m   2199[0m             [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   2200[0m [38;5;28;01mfinally[39;00m:
[1;32m   2201[0m     [38;5;28;01mif[39;00m bbox_inches [38;5;129;01mand[39;00m restore_bbox:

File [0;32m~/anaconda3/lib/python3.12/site-packages/matplotlib/backend_bases.py:2043[0m, in [0;36mFigureCanvasBase._switch_canvas_and_return_print_method.<locals>.<lambda>[0;34m(*args, **kwargs)[0m
[1;32m   2039[0m     optional_kws [38;5;241m=[39m {  [38;5;66;03m# Passed by print_figure for other renderers.[39;00m
[1;32m   2040[0m         [38;5;124m"[39m[38;5;124mdpi[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mfacecolor[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124medgecolor[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124morientation[39m[38;5;124m"[39m,
[1;32m   2041[0m         [38;5;124m"[39m[38;5;124mbbox_inches_restore[39m[38;5;124m"[39m}
[1;32m   2042[0m     skip [38;5;241m=[39m optional_kws [38;5;241m-[39m {[38;5;241m*[39minspect[38;5;241m.[39msignature(meth)[38;5;241m.[39mparameters}
[0;32m-> 2043[0m     print_method [38;5;241m=[39m functools[38;5;241m.[39mwraps(meth)([38;5;28;01mlambda[39;00m [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs: meth(
[1;32m   2044[0m         [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39m{k: v [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m kwargs[38;5;241m.[39mitems() [38;5;28;01mif[39;00m k [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m skip}))
[1;32m   2045[0m [38;5;28;01melse[39;00m:  [38;5;66;03m# Let third-parties do as they see fit.[39;00m
[1;32m   2046[0m     print_method [38;5;241m=[39m meth

File [0;32m~/anaconda3/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py:497[0m, in [0;36mFigureCanvasAgg.print_png[0;34m(self, filename_or_obj, metadata, pil_kwargs)[0m
[1;32m    450[0m [38;5;28;01mdef[39;00m [38;5;21mprint_png[39m([38;5;28mself[39m, filename_or_obj, [38;5;241m*[39m, metadata[38;5;241m=[39m[38;5;28;01mNone[39;00m, pil_kwargs[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[1;32m    451[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m    452[0m [38;5;124;03m    Write the figure to a PNG file.[39;00m
[1;32m    453[0m 
[0;32m   (...)[0m
[1;32m    495[0m [38;5;124;03m        *metadata*, including the default 'Software' key.[39;00m
[1;32m    496[0m [38;5;124;03m    """[39;00m
[0;32m--> 497[0m     [38;5;28mself[39m[38;5;241m.[39m_print_pil(filename_or_obj, [38;5;124m"[39m[38;5;124mpng[39m[38;5;124m"[39m, pil_kwargs, metadata)

File [0;32m~/anaconda3/lib/python3.12/site-packages/matplotlib/backends/backend_agg.py:446[0m, in [0;36mFigureCanvasAgg._print_pil[0;34m(self, filename_or_obj, fmt, pil_kwargs, metadata)[0m
[1;32m    441[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m    442[0m [38;5;124;03mDraw the canvas, then save it using `.image.imsave` (to which[39;00m
[1;32m    443[0m [38;5;124;03m*pil_kwargs* and *metadata* are forwarded).[39;00m
[1;32m    444[0m [38;5;124;03m"""[39;00m
[1;32m    445[0m FigureCanvasAgg[38;5;241m.[39mdraw([38;5;28mself[39m)
[0;32m--> 446[0m mpl[38;5;241m.[39mimage[38;5;241m.[39mimsave(
[1;32m    447[0m     filename_or_obj, [38;5;28mself[39m[38;5;241m.[39mbuffer_rgba(), [38;5;28mformat[39m[38;5;241m=[39mfmt, origin[38;5;241m=[39m[38;5;124m"[39m[38;5;124mupper[39m[38;5;124m"[39m,
[1;32m    448[0m     dpi[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mfigure[38;5;241m.[39mdpi, metadata[38;5;241m=[39mmetadata, pil_kwargs[38;5;241m=[39mpil_kwargs)

File [0;32m~/anaconda3/lib/python3.12/site-packages/matplotlib/image.py:1656[0m, in [0;36mimsave[0;34m(fname, arr, vmin, vmax, cmap, format, origin, dpi, metadata, pil_kwargs)[0m
[1;32m   1654[0m pil_kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mformat[39m[38;5;124m"[39m, [38;5;28mformat[39m)
[1;32m   1655[0m pil_kwargs[38;5;241m.[39msetdefault([38;5;124m"[39m[38;5;124mdpi[39m[38;5;124m"[39m, (dpi, dpi))
[0;32m-> 1656[0m image[38;5;241m.[39msave(fname, [38;5;241m*[39m[38;5;241m*[39mpil_kwargs)

File [0;32m~/anaconda3/lib/python3.12/site-packages/PIL/Image.py:2456[0m, in [0;36mImage.save[0;34m(self, fp, format, **params)[0m
[1;32m   2454[0m         fp [38;5;241m=[39m builtins[38;5;241m.[39mopen(filename, [38;5;124m"[39m[38;5;124mr+b[39m[38;5;124m"[39m)
[1;32m   2455[0m     [38;5;28;01melse[39;00m:
[0;32m-> 2456[0m         fp [38;5;241m=[39m builtins[38;5;241m.[39mopen(filename, [38;5;124m"[39m[38;5;124mw+b[39m[38;5;124m"[39m)
[1;32m   2458[0m [38;5;28;01mtry[39;00m:
[1;32m   2459[0m     save_handler([38;5;28mself[39m, fp, filename)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/home/tiagoburiol/metodos_numericos_em_python/2_ZEROS_DE_FUNCOES/png/bolzano.png'

